name: Twitter Code News

on:
 schedule:
   - cron: '10 07 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Crawl Tweets
      env:
        GMAIL_ID: ${{ secrets.GMAIL_ID }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
        TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
        TWITTER_OAUTH_TOKEN: ${{ secrets.TWITTER_OAUTH_TOKEN }}
        TWITTER_OAUTH_TOKEN_SECRET: ${{ secrets.TWITTER_OAUTH_TOKEN_SECRET }}
      run: |
        python ./main.py
