name: Twitter Code News

on:
 schedule:
   - cron: '30 06 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
         persist-credentials: false
         fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Crawl Tweets
      env:
        GMAIL_ID: ${{ secrets.GMAIL_ID }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
        TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
        TWITTER_OAUTH_TOKEN: ${{ secrets.TWITTER_OAUTH_TOKEN }}
        TWITTER_OAUTH_TOKEN_SECRET: ${{ secrets.TWITTER_OAUTH_TOKEN_SECRET }}
      run: |
        python ./main.py
    - name: Check modified
      id: check_modified
      run: |
        unset MODIFIED IS_MODIFIED
        if [[ `git status --porcelain` ]]; then MODIFIED='true'; fi
        echo "::set-output name=IS_MODIFIED::${MODIFIED}"
    - name: Commit files
      if: steps.check_modified.outputs.IS_MODIFIED == 'true'
      run: |
        git config --local user.email "dlsrb6342@gmail.com"
        git config --local user.name "dlsrb6342"
        git commit -m "Update last crwal time" -a
    - name: Push changes
      if: steps.check_modified.outputs.IS_MODIFIED == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.HUB_TOKEN }}

